### ISSUE TITLE
Fix Route::add('/test.html') in index.php

### ISSUE THREAD

**Issue by ImMaax** [steampixel/simplePHPRouter#12]
Lines 35-39, index.php:
```php
// Simple test route that simulates static html file
// TODO: Fix this for some web servers
Route::add('/test.html', function() {
  echo 'Hello from test.html';
});
```

This route isn't working on some web servers, like the PHP 7.4.1 Testing Server. The server will just search for the file in the file system instead of executing the route, even though the server has been configured correctly.

**Comment by steampixel** [comment]
OK. This sounds really weird. I will check this if i have time for that.

**Comment by steampixel** [comment]
Hey,

I cannot confirm this problem at the moment. I added a dockerfile for PHP 7.4.1
I also added a phpinfo() test route to the index.php file. So you can confirm the PHP version.
After running the container with the 7.4.1 image all routes are working as expected.

Do you have some additional information about your setup?

**Comment by ImMaax** [comment]
I'll test it again tomorrow and will probably send some more informations too.

**Comment by steampixel** [comment]
I will now close this issue because its a little bit outdated. Feel free to re-open it if this issue stays present.
