### ISSUE TITLE
putting simplePHPRouter on packagist.org?

### ISSUE THREAD

**Issue by ghost** [steampixel/simplePHPRouter#15]
Hi Stempixel,

Love you class, simple and neat!
Could be a great idea to put your class on Packagist don't you thing?
Also, giving it a proper namespace could be a great idea... 

Keep on your great work!

**Comment by ImMaax** [comment]
Definitively a great idea! It's already on the ToDo (see `README.md`), IIRC

**Comment by ghost** [comment]
Indeed,
Since it's in the todo for a while, SteamPixel must had forgotten... 
But the Namespace it's feasable quickly.

**Comment by steampixel** [comment]
Hey :-) I dont have forgotten this todo :-) But I thought this project was not important enough all the time. So I will now implement semver, namespacing and all the composer stuff in the next days or weeks.

**Comment by steampixel** [comment]
Done.
@ImMaax: Feel free to add your contributer info to the composer.json
