### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by Nex4T** [steampixel/simplePHPRouter#19]
When I go to my site with https, it goes to the home page as normal, but all the bottom pages cannot be called up, normal?

**Comment by steampixel** [comment]
Hey,
can you please explain what do you mean with "normal" and "bottom page"? Can you please post some example routes?

**Comment by steampixel** [comment]
If I understand you correctly you can call the / route but routes like /test.html will fail.
This is because you have not configurated the rewrite correctly. Please check this section of the docs: https://github.com/steampixel/simplePHPRouter#something-does-not-work

**Comment by steampixel** [comment]
I will now close this issue because of no reaction. Feel free to re open this issue if you need some help.
