### ISSUE TITLE
Route to a php page

### ISSUE THREAD

**Issue by antidote2** [steampixel/simplePHPRouter#2]
Hello, I'd like to use it for my site. I have an index.php which is a mix of html and <?php ... ?>.
so I need something like in my index.php... In the examples: there are only php function calls like echo ...;
will this work?

Route::add('/)',function(){
  include index.php;
},'get');

**Comment by steampixel** [comment]
Hey! Hope you had a nice weekend :-)
Yes of course! You can use any PHP-Code inside the route functions like this:
```
Route::add('/'),function(){
include('index.php');
},'get');
```

**Comment by steampixel** [comment]
Or if you need a dynamic file:

```
Route::add('/([a-z]*)'),function($filename){
if(file_exists($filename.'.php')){
include($filename.'.php');
}else{
echo 'File '.$filename.' not found';
}
},'get');
```
