### ISSUE TITLE
How i can rewrite /api/ to api.php in htaccess

### ISSUE THREAD

**Issue by nikkoenggaliano** [steampixel/simplePHPRouter#20]
I have file api.php like that. How i setting up this on htaccess?
```
route::add('/test', function(){
	echo 1;
},'GET');
// Run the router
Route::run('/api');
```

I tried like that but doesnt work

```
RewriteRule ^/api/(.*)$ api.php [QSA]
```

**Comment by steampixel** [comment]
Hey! If you don't want to use the index.php file and if you have an api.php inside an api folder like "api/api.php" instead please alter the .htaccess to the following:

```
# enable apache rewrite engine
RewriteEngine on

# set your rewrite base
# Edit this in your init method too if you script lives in a subfolder
RewriteBase /api/

# Deliver the folder or file directly if it exists on the server
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
 
# Push every request to index.php
RewriteRule ^(.*)$ api.php [QSA]
```

Take a look at RewriteBase and RewriteRule. I have altered the both lines for you. Note: Both, the api folder and the .htaccess file must be placed in your public reachable folder relative to your domain. So you can reach your api by connecting to https:/ /yourdomain.com/api/getProducts for example.

In your api.php file create now your routes and init the api. Also use your basepath inside the run method: 
```
...

Route::add('/getProducts', function() {
  echo 'List products...';
});

Route::run('/api');
```

**Comment by nikkoenggaliano** [comment]
Thank you.
