### ISSUE TITLE
Create a $basepath variable in index.php and auto prepend the navi

### ISSUE THREAD

**Issue by steampixel** [steampixel/simplePHPRouter#22]
This would improve the demo installation in subfolders

**Comment by ghost** [comment]
a quick fix could be to change the hrefs in the menu... per example:
`<li><a href="./">home</a></li>`

just insert a dot before the / so the link work within the directory where it is... ;)

Also, you should rename index.php to example.php... people don't read through the docs normally.

**Comment by florescuadrian86** [comment]
Hello. Now working but I have another problem.
I have in index.php this code:
`// Crazy route with parameters
Route::add('/(.*)/(.*)/(.*)/(.*)', function($var1,$var2,$var3,$var4) {
  navi();
  echo 'This is the first match: '.$var1.' / '.$var2.' / '.$var3.' / '.$var4.'<br>';
});`
I make click on this link http://localhost/simplePHPRouter/var1/var2/var3/var4 but show error 404.

Why no show this message : "echo 'This is the first match: '.$var1.' / '.$var2.' / '.$var3.' / '.$var4.'<br>';" ?
Can you help me. I test on xampp.

**Comment by steampixel** [comment]
@superdeeid Nice idea but this wont work on routes like /foo/bar/foo/bar. Because we need a path relative to the basepath. If you click on /foo/bar/foo/bar and then ./test.html would point to /foo/bar/foo/test.html

I think it would be cleaner to use a $basepath instead.

**Comment by steampixel** [comment]
I now created a BASEPATH constant for the example.
