### ISSUE TITLE
Setup with subfolder works fine but doesn't match base path

### ISSUE THREAD

**Issue by piaaaac** [steampixel/simplePHPRouter#23]
My project lives in `/report-2019`. I configured this base path both in .htaccess
```
RewriteBase /report-2019
```
and on Route start 
```
Route::run("/report-2019")
```
I defined some routes, which work fine, but the "/" route triggers the `pathNotFound` function.

```
use Steampixel\Route;

// should match /report-2019/, but it doesn't
Route::add('/', function () {
  die('Welcome :-)');
});

// matches /report-2019/lorem-ipsum
Route::add('/([a-zA-Z\-0-9]+)', function ($page) {
  $_GET = [ 
    "type" => "base",
    "slug" => $page 
  ];
});

// matches /report-2019/activities/lorem-ipsum
Route::add('/activities/([a-zA-Z\-0-9]+)', function ($activity) {
  $_GET = [ 
    "type" => "activity",
    "slug" => $activity 
  ];
});

Route::pathNotFound(function () {
  echo "> > > 404 < < <";
});

Route::run("/report-2019");
```

Hope I'm not missing something really obvious. Thanks for any help!

**Comment by steampixel** [comment]
Hey,

I think you have found some kind of a bug. I am facing the same issue. The router cuts away the trailing slash from the root basepath. Because of that the router tries to match /report-2019 instead of /report-2019/

For now: Try setting the third parameter of the run method to true:

Route::run('/report-2019', false, true, false);

**Comment by piaaaac** [comment]
Hi, 
with this parameter it's working, and so far it doesn't seem to have other side effects.
I'll keep you posted if I find any. Thanks.

**Comment by steampixel** [comment]
The side effect it that now calls with trailing slash like /aTrailingSlashDoesNotMatter and /aTrailingSlashDoesNotMatter/ will be treated differently. One of them will lead into a 404 now.

**Comment by steampixel** [comment]
Fixed it in https://github.com/steampixel/simplePHPRouter/releases/tag/0.4.1
