### ISSUE TITLE
how to change route 404/405 to another path?

### ISSUE THREAD

**Issue by steampixel** [steampixel/simplePHPRouter#30]
how to change route 404/405 to another path? thanks.

_Originally posted by @Hillzacky in https://github.com/steampixel/simplePHPPages/issues/1#issuecomment-665687342_

**Comment by Hillzacky** [comment]
Is the code when the transfer is saved in the added route? what I meant in this line of code:
```
    // No matching route was found
    if(!$route_match_found){

      // But a matching path exists
      if($path_match_found){
        header("HTTP/1.0 405 Method Not Allowed");
        if(self::$methodNotAllowed){
          call_user_func_array(self::$methodNotAllowed, Array($path,$method));
        }
      }else{
        header("HTTP/1.0 404 Not Found");
        if(self::$pathNotFound){
          call_user_func_array(self::$pathNotFound, Array($path));
        }
      }

    }
```
Is there no other way? the problem is like calling inside (include).

**Comment by steampixel** [comment]
Sorry. I don't understand your problem. Feel free to reopen the issue.
