### ISSUE TITLE
Include PHP file with variables in index.php , undefined in routed pages

### ISSUE THREAD

**Issue by da-kicks-87** [steampixel/simplePHPRouter#31]
Hello,

The routing works, but I am having PHP variable problems when echoing from routed pages. They are undefined. 

When I echo **$tag_line** from **index.php** it works, but not from **home.php**. Why is this?

Example of what i have:

### **index.php**

//INC php Variables
require __DIR__ . '/src/inc/company-info.php';
require __DIR__ . '/config.php';

// Use this namespace
use Steampixel\Route;

// Include route class
include 'src/inc/Route.php';

// Define a global basepath
define('BASEPATH','/');

Route::add('/', function() {
  require __DIR__ . '/src/views/home.php';
});

### **company-info.php**

$tag_line = "Demo Tag Line";

### **home.php**

 echo $tag_line; 

----------

**Comment by steampixel** [comment]
Hey,
this is not a router issue. This is a general PHP behavior.

You home.php file gets included inside of an anonymous function. You cannot access variables defined in the global scope from within a functions local scope. In this case you have two options:

1. Global your variable
```
Route::add('/', function() {
global $tag_line;
require DIR . '/src/views/home.php';
});
```
2. Inject the variable to the function using the "use" statement (I would prefer this)
```
Route::add('/', function() use($tag_line) {
require DIR . '/src/views/home.php';
});
```
Please read this to understand the mechanism of this: https://www.php.net/manual/en/language.variables.scope.php
