### ISSUE TITLE
Header & Footer

### ISSUE THREAD

**Issue by NSady** [steampixel/simplePHPRouter#38]
Hi,

Is there a way to add an include/require on every single route, without actually typing it for each route? For example, I have 10 different routes that should all include a header.php file. Looking for a wildcard route I guess to respond to all routes, and then the individual route.

Thanks!

**Comment by steampixel** [comment]
Hey @nsraven34,
you could add a wildcard route before your define the content routes. Do not forget to enable the multi match mode for the router: https://github.com/steampixel/simplePHPRouter/blob/master/README.md#enable-case-sensitive-routes-trailing-slashes-and-multi-match-mode

This mode enables the router to execute more than one route at the same time. Warning: this mode can lead to unexpected results. You should be sure that the routes are unique enough. Example:
```
Route::add('/pages/([a-z-0-9-]*)', function($slug) {
  // include the header for all pages
});

Route::add('/pages/my-page', function($slug) {
  // include the contents for my page
});

Route::add('/pages/another-page', function($slug) {
  // include the contents for another page
});

// Run the router with multi match mode
Route::run(BASEPATH, false, false, true);
```

**Comment by steampixel** [comment]
If you want to include your header on EVERY route. Just include it before the router run method without wrapping it into a Route::add.

**Comment by Nex4T** [comment]
and what is if he want to give the header vars from the route?
He need to put it in the route.

**Comment by steampixel** [comment]
Another suggestion for this kind of problem (untested pseudocode):
```
Route::add('/pages/([a-z-0-9-]*)', function($slug) {
  // include the header for all pages
  include('header.php');

  switch ($slug) {
    case 'my-page':
        include('my-page.php');
        break;
    case 'another-page':
        include('another-page.php');
        break;
    case 'third-page':
        include('third-page.php');
        break;
}

  // include the footer for all pages
  include('footer.php');
});
```

**Comment by NSady** [comment]
Thank you!
