### ISSUE TITLE
featureRequest: methode to Return all known routes

### ISSUE THREAD

**Issue by cereal2nd** [steampixel/simplePHPRouter#42]
it would be nice (to create some sort of help url) that there would be a methode to fetch all known routes.

this would make it easy to cerate a help page

**Comment by steampixel** [comment]
Hey @Cereal2nd,
great idea. Please check out this branch and tel me if this fits the needs: https://github.com/steampixel/simplePHPRouter/tree/known-routes
I have added a new method `Route::getAll()`. I also added a new example to the bottom of the index.php file.
On top of that you could use a library like https://github.com/hoaproject/Regex to generate working example links for the different expressions.

**Comment by cereal2nd** [comment]
This is exactly what i was looking for (and did in my lcoal install)

**Comment by i3iorn** [comment]
@steampixel - Hello, do you plan on merging this with master?

**Comment by steampixel** [comment]
Hey,
merged this and releases 0.7.0: https://github.com/steampixel/simplePHPRouter/releases/tag/0.7.0
