### ISSUE TITLE
Please also add middleware implementation through this router

### ISSUE THREAD

**Issue by kingx619** [steampixel/simplePHPRouter#44]
Can you also implement adding middleware through this routing system ...it would be much better.

**Comment by steampixel** [comment]
Hi,
this router is already some kind of a middleware. Its between the HTTP request and your controller logic. Could you please add some pseudo code or some example code? What is the concrete problem? Or what is the concrete task of your middleware?

**Comment by kingx619** [comment]
How to implement User roles(superAdmin , admin ,simple user)  logic to prevent  access to certain routes using this router .Also how can I implement CSRF attacks without having a specific implementation of middleware or add any kind of middleware stack added to this router

**Comment by steampixel** [comment]
Hi,
this is a simple router. For now, I don't want to increase the complexity any further.
You could check the user like that:
```
Route::add('/admin/', function() {
  if(Auth::isAdmin()){
    return 'Welcome :-)';
  }
});
```

Or like this:
```
if(Auth::isAdmin()){
  Route::add('/admin/', function() {
      return 'Welcome :-)';
  });
}
```
I would do the same for CSRF. Call your CSRF class from within a route and verify the tokens. Or do you see an easy way to implement that?
