### ISSUE TITLE
PUT Request CORS Error

### ISSUE THREAD

**Issue by flamurbeqiraj** [steampixel/simplePHPRouter#45]
While building the middleware, I managed to do the GET, POST request but PUT request seems not to work as it should, It's showing CORS Error. Has anyone tested this case, what is the problem here!?

**Comment by flamurbeqiraj** [comment]
Btw, I tested it with Postman, I tested the filename.php directly for the PUT request and it works like a charm, there is something wrong with the PUT Route definitely.

**Comment by steampixel** [comment]
Hey! I think the easiest way for me to debug this would be to have access to your code. Could you please share your code?

**Comment by flamurbeqiraj** [comment]
The index file:

Route::add('/project/u', function() {
    require_once('put/project.php');
}, 'put');

Here is the responding file:
<?php
    header('Access-Control-Allow-Origin: *');
    header('Content-Type: application/json');
    header('Access-Control-Allow-Methods: PUT');
    header('Access-Control-Allow-Headers: Access-Control-Allow-Headers,Content-Type,Access-Control-Allow-Methods,Authorization,X-Requested-With');
echo 'Reaching successfuly!';

Like i said, with real url the put request is working fine, when I access the router its not reaching.

**Comment by steampixel** [comment]
What is inside your put/project.php?

**Comment by flamurbeqiraj** [comment]
Im sorry I don't know why the code was not pasted, anyway here it is, it's a simple code that should runn without any smallest problem: 

<?php
    header('Access-Control-Allow-Origin: *');
    header('Content-Type: application/json');
    header('Access-Control-Allow-Methods: PUT');
    header('Access-Control-Allow-Headers: Access-Control-Allow-Headers,Content-Type,Access-Control-Allow-Methods,Authorization,X-Requested-With');
    
    echo 'Responding successfuly';

**Comment by flamurbeqiraj** [comment]
Sorry, here is the actual code that should really work, because it has no complications, the semilar code works just fine for GET and POST, but checked and verified for PUT and DELETE there is something wrong:

`<?php
    header('Access-Control-Allow-Origin: *');
    header('Content-Type: application/json');
    header('Access-Control-Allow-Methods: PUT');
    header('Access-Control-Allow-Headers: Access-Control-Allow-Headers,Content-Type,Access-Control-Allow-Methods,Authorization,X-Requested-With');
    echo 'Responding successfuly';`

**Comment by steampixel** [comment]
Hi, I will try to put this on my task list for the next days.

**Comment by steampixel** [comment]
Ok. Your application tries to load some data via Javascript from a server (Or does any similar). I think your Access-Control-Allow-Methods and your Access-Control-Allow-Headers does not make sense inside this route. Because that headers are preflight request headers (https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request). Your browser would expect to get this headers by sending an OPTIONS Request to your route. This happens BEFORE the put request will fire. So please try this:

```
Route::add('/project/u', function() {
  header('Access-Control-Allow-Methods: PUT');
  header('Access-Control-Allow-Headers: Access-Control-Allow-Headers,Content-Type,Access-Control-Allow-Methods,Authorization,X-Requested-With');
}, 'options');

Route::add('/project/u', function() {
  header('Access-Control-Allow-Origin: *');
  header('Content-Type: application/json');
  echo 'Responding successfuly';
}, 'put');
```
I have put the code directly inside the route for better readability. But this is the same as including a file.
