### ISSUE TITLE
proper way of a 404 error page display

### ISSUE THREAD

**Issue by ghost** [steampixel/simplePHPRouter#49]
hi, really love your router, simple straight to the point.
One question tho : what's the proper way of display a 404 error page when a syntax is already filled in a Route::add() without duplicating the 404 error page procedure in the Route::pathNotFound() (ie: after validating that the $path isn't a valid page/index) ?

a was thinking of returning a special code returned from the function() but it doesnt work since it's a function created 'on the fly'.

Regards,

**Comment by steampixel** [comment]
Hi @laboxmedia ,
you should call the same routine as in your Route::pathNotFound() method. In case you are using some kind of a templating engine: Just call the same class/method again in your add() method. Its like the navigation inside the example page of this project. I don't want to repeat this navigation on each route.

**Comment by ghost** [comment]
actually, that's a good idea. thx!
