### ISSUE TITLE
haeder Problems

### ISSUE THREAD

**Issue by jonathankfmn** [steampixel/simplePHPRouter#51]
Hello,

first the Router is very good and easy to handle, but there is a Problem when I include a file and in this file I like to change the header to download or display a file this doesn't work, because you have to change the haeder before you output some code / HTML.
Are there any solutions for that problem?

**Comment by ibnsultan** [comment]
could you please provide a code sample, coz I've tried to create some imaginative sample of what you say, and it works fine

**Comment by jonathankfmn** [comment]
clear, 

```
<?php
require_once './php/route.php';
define('BASEPATH','/');
Route::add('/open',function() {
    include('./php/open.php');
}, 'post');
Route::pathNotFound(function($path) {
    header('HTTP/1.0 404 Not Found');
    echo 'Error 404 :-(<br>';
    echo 'The requested path "'.$path.'" was not found!';
});
Route::methodNotAllowed(function($path, $method) {
    header('HTTP/1.0 405 Method Not Allowed');
    echo 'Error 405 :-(<br>';
    echo 'The requested path "'.$path.'" exists. But the request method "'.$method.'" is not allowed on this path!';
});
Route::run(BASEPATH);
```

that was my index.php file 
and there is my open.php

```
<?php
    $filepath = "../".$_POST['path'];
    $filename = $_POST['name'];
    $mime = get_mime_type($filepath);
    $file = file_get_contents($filepath);

    header('Content-Type: text/plain');
    header('Cache-Control: public, must-revalidate, max-age=0'); // HTTP/1.1
    header('Pragma: public');
    header('Expires: Sat, 26 Jul 1997 05:00:00 GMT'); // Date in the past
    header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
    header('Content-Length: '.strlen($file));
    header('Content-Disposition: inline; filename="'.basename($filepath).'";');
    ob_clean(); 
    flush(); 
    echo $file;
```


I have a formular on an other page wich send the needed data and when I set the action directly on the open.php file everything worked fine. But when the direction points to the registered route there is only a white page.

**Comment by ibnsultan** [comment]
Iis that all? coz it seems there are some files still missing but anyway have you tried ['get', 'post'] to your route as request methods

**Comment by jonathankfmn** [comment]
no thats not all but that are the important files from my test setup. I have just tested whether this works with ['get', 'post'] and unfortunately that doesn't work either.

**Comment by ibnsultan** [comment]
look here `$filename = $_POST['name'];`
your code uses post constant for files, try $_FILES['name'] like `$filename = $_FILES['name'];`
if you're using an html form to post your data make sure you use multipart enctype

**Comment by steampixel** [comment]
I don't understand what the current problem is. Is there a white page? Or is there an error message? Have you error logging or error messages enabled in PHP?

But there is a security issue inside your open.php.You should add
`$filepath = str_replace('..','',$filepath); ` (untested)
or something like that. An attacker could use a malicious request to download server files through your app using a path traversal attack. Keep in mind that path could be something like ../../../ and name could be .htpasswd or similar like this. So cut away double dots.

**Comment by steampixel** [comment]
Please copy this to the top of your index.php to enable the complete error output:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by jonathankfmn** [comment]
Thanks for your help. Of course, I have fixed the security error. I also enabled the full error reporting in the files index.php and open.php, but there is no error output. In the Firefox developer tools, I can see the header and there is everything fine (for example, there you find the filename).
My problem is that I have a form (for downloading a file) on another page and when I set the action to the path of the open.php file everything works fine. But I like to use the Router and when I set the action to "/open" there's only a white page but with the right header.

**Comment by jonathankfmn** [comment]
Sorry, I have found the error. The error was not the header or the filename. The file open.php is stored in a subfolder, and I din'd specified the path correctly... I had forgotten that the file will be included.

**Comment by steampixel** [comment]
Hey @thonajan ,

I'm glad you found the error.

You should consider using require() instead of include() since this is a critical part of your app. include() means the file will only be loaded if it exists but require() will throw an error if the file is missing or the path is wrong.

**Comment by jonathankfmn** [comment]
Hello @steampixel,
Thanks for that information. I will change that definitely.
Also thank you very much for your help!
