### ISSUE TITLE
multilanguage router

### ISSUE THREAD

**Issue by sanater** [steampixel/simplePHPRouter#54]
Hi, how can i multi language router this class?

site.com/en
site.com/tr
site.com/fr

**Comment by steampixel** [comment]
Hi,
what about something like this (untested):
```
Route::add('/([a-z]*)/([a-z-0-9-]*)', function($lang, $page) {
    echo 'Load page '.$page.' with language code '.$lang;
});
```

**Comment by sanater** [comment]
thank you

**Comment by sanater** [comment]
how can i assign variable for default language?

**Comment by sanater** [comment]
please sample or demo full page?
