### ISSUE TITLE
Grouping/Sub-Route Request.

### ISSUE THREAD

**Issue by compilekaiten** [steampixel/simplePHPRouter#62]
Create a group name, which becomes the Prefix for every route inside it.

Or is this already possible somehow?

```php
Route::group('/prefix', function() {

    Route::add('/', function () {
        echo "This Route is: /prefix";
    });

    Route::add('/user', function() {
        echo "This Route is: /prefix/user";
    });
    
});
```

**Comment by splashsky** [comment]
I've already added this functionality in my fork. You can look at the code and implement a PR here, if you'd like.

[https://github.com/splashsky/simplerouter/pull/10](https://github.com/splashsky/simplerouter/pull/10)

**Comment by steampixel** [comment]
@compilekaiten I want to stay basic with this router. So I will not implement a grouping feature at the moment. But as @splashsky already mentioned you can use this code
