### ISSUE TITLE
"Use return instead of echo": doesn't work when the function is called by pathNotFound()

### ISSUE THREAD

**Issue by Mutusen** [steampixel/simplePHPRouter#65]
Hi, as it says in the title:

> You don't have to use `echo` to output your content. You can also use the `return` statement. Everything that gets returned is echoed automatically.

This is not true when the function is called by `pathNotFound()`.

I guess line 131 of `Route.php` should be changed to something like:

```php
if($return_value = call_user_func_array(self::$pathNotFound, Array($path,$method))) {
  echo $return_value;
}
```

**Comment by steampixel** [comment]
@Mutusen thanks for reporting this.
Fixed it in the latest release: https://github.com/steampixel/simplePHPRouter/releases/tag/0.7.1
