### ISSUE TITLE
Using query parameters

### ISSUE THREAD

**Issue by der-jung** [steampixel/simplePHPRouter#68]
Hi,

i like your Router implementation! Currently i am trying to math a path like this "/pictures?page=5&pageSize=10" where the numbers should be handed to the function but all i get is a 404.
My route definition is:

```
Route::add('/pictures\\?page=([0-9]*)&pageSize=([0-9]*)', function ($page, $pageSize) {
 // [...]
}, 'get');
```

Am i doing something wrong or does the implementation does not support these kind of routes? There seems not to be an example for this kind?

Best Regards!

**Comment by steampixel** [comment]
Hi,

the query string (?x=y&foo=bar) is not part of the URI path. The query string is parsed by PHP and available through $_GET or $_REQUEST. So this will not work. This router will match pathes only:

```
Route::add('/pictures', function () {
  // Check the query string params in here
  if(is_numeric($_GET['page'])) {
    echo 'page is numeric';
  }
}, 'get');
```

Or rewrite your params like this:

```
Route::add('/pictures/page/([0-9]*)/size/([0-9]*)', function ($page, $pageSize) {
 // [...]
}, 'get');
```

**Comment by steampixel** [comment]
Explanation: This router will simulate virtual files and folders. But the query string is not part of the servers file system. So this is not supported.

**Comment by der-jung** [comment]
Thanks for your quick help! I see your pint and now it works!
