### ISSUE TITLE
How to define if it's a page or an index...

### ISSUE THREAD

**Issue by ghost** [steampixel/simplePHPRouter#7]
Nice piece of script you got there. Great job !

just one question : How do to manage to test if the giving url must be a page or a category index. Since we must hardcode the path from the beginning ?

Example:
```
www.domain.com/name -> could be a page
www.domain.com/name -> could be an index of a category named 'name'
```

Maybe by doing a Query into the database ? If that's the case, why not just parse the url into the database to see if there is a match (of course, there's a field for the match url syntax).

**Comment by steampixel** [comment]
Hey,
normaly a page URL looks like http://foo.bar/page
A folder URL looks like http://foo.bar/folder/
Noticed the trailing slash?

So first of all you have to enable the trailing slash detection like described in the readme:

> The second and third parameters of Route::run('/', false, false); are both set to false by default. You can enable case sensitive mode by setting the second parameter to true. By default the router will ignore trailing slashes. Set the third parameter to true to avoid this.

Then it should make a difference if you use www.domain.com/name or www.domain.com/name/

Is that the information you was looking for?

If you store all your pathes inside a database you must create a route, that directs the request to the database. Example: If you have your blog posts inside the database, you have to create a static route like this:

Route::add('/posts/([a-z]*)',function($post_name){
  // Select the post with the name $post_name from db
  // If the post was found print it
  // If the post was not found send a 404 header
});
This route will hand over the name of the post to the database.

**Comment by ghost** [comment]
thx !
i was under the impression to not having a trailing slash at the end to know if we must display a post/page or a category... You way is simplier.
