### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by elymatos** [steampixel/simplePHPRouter#8]
Hi, what is the orientation if we want to use optional parameters in the route definition?
Thanks

**Comment by steampixel** [comment]
Hey,

currently I have no time to test this idea but try something like this:

```
Route::add('/user/([0-9]*)/edit/([a-z]*)?',function($id, $optional){
  echo 'Edit user with id '.$id.'<br/>';
  echo 'The optional parameter is '.$optional.'<br/>';
},'get');
```

Noticed the question mark in the regexp? This should make the second parameter optional. But I have not tested this. Please try this and report back the results please.

**Comment by ghost** [comment]
It's better to make two route path for that... So the values are consistent. example : 
`Route::add('/user/([0-9]*)',function($id){
 var_dump($id);
},'get');

Route::add('/user/([0-9]*)/edit/([a-z]*)',function($id,$name){
 var_dump($id,$name);
},'get');`

If you try : domain.com/user/14/edit/daniel it will try to match against the first route:add and then go to the second one.

**Comment by elymatos** [comment]
Thanks for answers!
My use case is like 'module/controller/action/id' where action can be optional (in this case, 'main') and 'id' is optional too.
I've tried with '?' but it doesn't work as expected, because the '/' must be optional too.
Then for while I prefer to define three routes and to be sure about the parameters.
Thanks for sharing!
